# Generated by Django 3.2.7 on 2021-10-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_rekomendasi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelatihan',
            old_name='tanggal_pelatihan',
            new_name='tanggal_mulai',
        ),
        migrations.AddField(
            model_name='pelatihan',
            name='tanggal_selesai',
            field=models.DateField(null=True),
        ),
    ]
