# Generated by Django 3.2.7 on 2021-10-04 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_rekomendasi', '0002_auto_20211004_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelatihan',
            name='rating_pelatihan',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Rekomendasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripsi', models.TextField(null=True)),
                ('penanggung_jawab', models.CharField(choices=[('RB', 'Renbang'), ('EV', 'Evalap'), ('TU', 'TU'), ('PY', 'Penyelenggaraan')], default='TU', max_length=2)),
                ('diselesaikan', models.BooleanField(default=False)),
                ('nama_pelatihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring_rekomendasi.pelatihan')),
            ],
        ),
    ]
